### PR TITLE
updating last section

### PR DESCRIPTION
**Pull request by aspina7**
@AmyMikhail - finishing edits. 
Only thing I dont understand (and I might have missed this as dont have the latest mixed methods case study) - is why are we presenting unweighted counts?

### CODE REVIEW

**Comment by AmyMikhail** [comment]
@aspina7 the unweighted counts are what is presented in the STATA version of the guide - to be honest I'm not sure why that is the case either, but I think it might have been just to present a descriptive summary before presenting the actual weighted results.  I will check with Kostas.

I have incorporated your session 5 edits into my latest commit, which you can use for signing off if you haven't already sent a previous version.  However there has been some useful feedback after the case study from some of the other R facilitators and Kostas has asked me to incorporate that feedback into the final version next week.

Here are the main points:

1. Package installs:  CRAN packages were ok but the two Github ones (`epikit` and `sitrep`) caused lots of difficulties.  Some of these were due to institutional restrictions, but in other cases we had an API limit exceeded error from Github, because too many people were trying to install the packages at the same time (we think this was the cause).  In any case, Joana came up with a good suggestion to bundle the necessary packages with renv - this will be a heavy folder, but it can be uploaded onto EVA and for the next year participants can just download it from there and have everything they need.
2. Dplyr workflow pipes: some facilitators noticed that participants preferred to see what each line of code was doing and inspect the result, before going onto the next one, rather than running a whole series of piped commands.  This is especially true given the content of the vaccination coverage survey case study is quite heavy, is now being done in the first year of the fellowship when many people have not yet done routine surveillance yet (and therefore may not yet appreciate the need for workflows).  In addition this cohort was not familiar with sampling at all, so they really needed everything conceptually broken down.  The suggestion is to present one example of each new major command (especially the ones linked to key concepts in the case study) not piped at first (as I did with prevalence ratio calculations in session 5) and then pipe them afterwards to create the summary tables.
3. .Rmd vs R script: while the .Rmd was useful to have as a guide, for running code line by line (as above) an accompanying script may work better.   The level of R abilities in this group was very mixed and due to the length of the case study, the strategy was shifted towards discussing the results tables with less emphasis on discussing the code / how they were produced and providing this more as a reference for their own use later.  In some groups it was not possible for participants to run the code, so from session 4 if online it was briefly demonstrated by facilitators and where face to face they just focused on discussing the results tables in the guide.  Other groups only had time to copy/paste or just run the code directly from the .Rmd.  There is emerging concensus that the case study may need to be split into two, one focusing on the concepts (sessions 1 to 3) and the other on analysis (sessions 4 to 5).  However I don't think it is any harm to have all sessions demonstrated in R, as people will still find this a useful reference when they do their own studies.
4.   Not directly related, but there is some frustration among the fellows as they feel that the case studies have been converted to R without a proper introduction on how to use it.  This was not a criticism of this case study but more a general recognition of need.  I don't think it necessarily changes much how the content of the R companion is structured (other than introducing examples without pipes as above) but is more something that needs to be tackled as a separate issue.

**Comment by aspina7** [comment]
@AmyMikhail 

> unweighted counts are what is presented in the STATA version of the guide

Okay - it actually makes no sense, but if thats how they have it then just leave. 

> session 5 edits [...]  for signing off [...] Kostas has asked me to incorporate that feedback into the final version next week.

Will use the current version for sign-off to keep the contact moving and ensure they pay on time. Feedback should be incorporated though yes and also having it as a completely standalone text as kostas asked. See my responses to feedback points below. 

> 1. Package installs:  CRAN packages were ok but the two Github ones (`epikit` and `sitrep`) caused lots of difficulties. 

I would not get in to using {renv} with new users - it gets very complex very quickly and then people wont be able to update their own packages without a lot of cognitive overhead. Installing of {sitrep} and {epikit} will be sorted by the next course and will just be CRAN installs, as we are finalising that contract (and those are the only github packages). 
A simpler alternative is to just have a big zip folder with all the necessary packages, which people can then install manually if they are having issues. 
There is some work happening around using r-universe and versioning, that would simplify installs as well.
I will update the case studies when this happens, before next years module - leave as is for now. 

> 2. Dplyr workflow pipes: some facilitators noticed that participants preferred to see what each line of code was doing and inspect the result, before going onto the next one, rather than running a whole series of piped commands.  

Yes, I agree with this - in general we have taken the approach to not chain more than 2-3 pipes together, for exactly that purpose. 

> 3. .Rmd vs R script: while the .Rmd was useful to have as a guide, for running code line by line (as above) an accompanying script may work better.  

I would leave as an RMD - and provide a clean RMD in a "report-type format" - but basically just strip away all the extra text. 
This is the same as we have done for previous courses and was well received. Using an r-script does not really make sense because that is not what people will use in real-world practice. 


> 4. Not directly related, but there is some frustration among the fellows as they feel that the case studies have been converted to R without a proper introduction on how to use it.  This was not a criticism of this case study but more a general recognition of need.  I don't think it necessarily changes much how the content of the R companion is structured (other than introducing examples without pipes as above) but is more something that needs to be tackled as a separate issue.

Yeap have also received this feedback. Thats an overall epiet issue though in that they need to have a proper R intro-course at the beginning of the two years and build from there, it is pointless having fellows doing an advanced course like this with dense code but without having done any of the basics.

**Comment by AmyMikhail** [comment]
Thanks @aspina7 - just wanted to clarify what you mean with the .Rmd - to have two versions, one with the guide and all the explanations and then a second one with only code chunks and minimal text explaining which steps / tasks each code chunk is related to?

**Comment by aspina7** [comment]
yes exactly - effectively the same thing you would do for having an r-script but just leave it in an rmd for functionality.

**Pull request closed without merging**
